auths/urls.py
from django.urls import path

from . import views

app_name = 'auths'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout, name='logout'),

    path('home/', views.home_view, name='home'),
    path('article/', views.article_view, name='article'),
    path('article_create/', views.article_create_view, name='article_create'),
    path('article_create_post/', views.article_create_post, name='article_create_post'),
    path('<int:article_id>/article_detail/', views.article_detail_view, name='article_detail'),

    path('login_post/', views.login_post, name='login_post'),
    path('register_post/', views.register_post, name='register_post'),

    path('<int:user_id>/update_view/', views.update_view, name='update_view'),
    path('<int:user_id>/update_post/', views.update_post, name='update_post'),

    path('<int:user_id>/delete/', views.delete, name='delete'),
]

keyextractor/urls.py
from django.urls import path

from . import views

app_name = 'keyextractor'
urlpatterns = [
    path('', views.home_view, name='home'),
    path('article_create/', views.article_create_view, name='article_create'),
    path('article_create_post/', views.article_create_post, name='article_create_post'),
    path('<int:article_id>/article_detail/', views.article_detail_view, name='article_detail'),
    path('<int:article_id>/article_delete/', views.article_delete, name='article_delete'),
    path('<int:article_id>/article_analyze/', views.article_analyze, name='article_analyze'),
    path('<int:article_id>/article_analyze_basic/', views.article_analyze_basic, name='article_analyze_basic'),
    path('<int:article_id>/article_update/', views.article_update_view, name='article_update'),
    path('<int:article_id>/article_update_post/', views.article_update_post, name='article_update_post'),
    path('<int:article_id>/reset_extraction/', views.reset_extraction, name='reset_extraction'),
    path('reset_all_extraction/', views.reset_all_extraction, name='reset_all_extraction'),
    path('statistics/', views.statistics, name='statistics'),
    path('import_pdf/', views.import_pdf, name='import_pdf'),
    path('extract_all_keyword/', views.extract_all_keyword, name='extract_all_keyword'),
    path('extract_all_keyword_basic/', views.extract_all_keyword_basic, name='extract_all_keyword_basic')
]

simpleauth/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auths/', include('auths.urls')),
    path('keyextractor/', include('keyextractor.urls')),
    path('admin/', admin.site.urls),
]

keyextractor/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    original_keyword = models.TextField()
    extracted_keyword = models.TextField()
    accuracy = models.CharField(max_length=200)
    load_time = models.CharField(max_length=20)
    extracted_keyword_ori = models.TextField()
    accuracy_ori = models.CharField(max_length=200)
    load_time_ori = models.CharField(max_length=20)

    def __str__(self):
        return self.title

class Katadasar(models.Model):
    katadasar = models.CharField(max_length=70)
    tipe_katadasar = models.CharField(max_length=25)

    def __str__(self):
        return self.katadasar

keyextractor/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

keyextractor/controllers.py
from nltk.tokenize import sent_tokenize, word_tokenize, WordPunctTokenizer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import re
import networkx as nx
# import PyPDF2
import tika
tika.initVM()
from tika import parser

from .models import Katadasar

# Tokenize
class Tokenize:

    def sentence_token(text):
        return text.split('. ')

    def word_token(text):
        result = text.lower()
        result = re.sub(r'[^a-z0-9 .,:/\(\)-]', ' ', result, flags = re.IGNORECASE|re.MULTILINE)
        result = re.sub(r'[,:/\(\)]', ' , ', result, flags = re.IGNORECASE|re.MULTILINE)
        result = re.sub(r'[.]', ' . ', result, flags = re.IGNORECASE|re.MULTILINE)
        result = re.sub(r'( +)', ' ', result, flags = re.IGNORECASE|re.MULTILINE)
        return result.strip().split(' ')

# Stemming with Sastrawi Library
def stemming(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    return stemmer.stem_token(text)


# Import PDF
class ImportPdf:

    def __init__(self, url):
        parsed = parser.from_file('D:\\College\\Script C\\data\\UNIMED Articles\\'+url)
        self.page_content = parsed["content"]
    
    def get_all_content(self):
        return self.page_content
    
    def get_title(self):
        temp_title = self.page_content[170:400].split(' ')
        title = ''
        for word in temp_title:
            if word.isupper() and len(word) > 1:
                title += word+' '
        return title

    def get_content(self):
        temp_abs = self.page_content[300:3000]
        temp_isi = self.page_content[1000:len(self.page_content)]

        if temp_abs.find("Kata Kunci") > -1:
            abstrak = temp_abs[temp_abs.find("Abstrak"):temp_abs.find("Kata Kunci")]
        elif temp_abs.find("Kata kunci") > -1:
            abstrak = temp_abs[temp_abs.find("Abstrak"):temp_abs.find("Kata kunci")]
        elif temp_abs.find("Keywords") > -1:
            abstrak = temp_abs[temp_abs.find("Abstrak"):temp_abs.find("Keywords")]
        
        if abstrak.find("Abstrak—") > -1: abstrak = abstrak.replace("Abstrak—", "")
        else: abstrak = abstrak.replace("Abstrak —", "")

        abstrak = abstrak.replace("\n", " ")
        isi = temp_isi[temp_isi.find("PENDAHULUAN"):temp_isi.find("REFERENSI")]
        isi = isi.replace("\n", " ")
        isi = isi.replace("PENDAHULUAN", "")
        isi = isi.replace("Gbr.", "")
        repl = re.compile(re.escape("CESS (Journal of Computer Engineering System and Science)"), re.IGNORECASE)
        isi = repl.sub('', isi)
        content = {
            'abstrak': abstrak,
            'isi': isi,
        }
        return content

    def get_keyword(self):
        temp_key = self.page_content[200:4000]
        if temp_key.find("Kata Kunci") > -1:
            keywords = temp_key[temp_key.find("Kata Kunci"):temp_key.find("I. PENDAHULUAN")]
            if keywords.find("Kata Kunci—") > -1: keywords = keywords.replace("Kata Kunci—", "")
            else: keywords = keywords.replace("Kata Kunci —", "")
        elif temp_key.find("Kata kunci") > -1:
            keywords = temp_key[temp_key.find("Kata kunci"):temp_key.find("I. PENDAHULUAN")]
            if keywords.find("Kata kunci—") > -1: keywords = keywords.replace("Kata kunci—", "")
            else: keywords = keywords.replace("Kata kunci —", "")
        elif temp_key.find("Keywords") > -1:
            keywords = temp_key[temp_key.find("Keywords"):temp_key.find("I. PENDAHULUAN")]
            if keywords.find("Keywords—") > -1: keywords = keywords.replace("Keywords—", "")
            else: keywords = keywords.replace("Keywords —", "")

        keywords = re.sub(r'[^a-z0-9 ,-]', ' ', keywords, flags = re.IGNORECASE|re.MULTILINE)

        return keywords

def handle_uploaded_file(f):
    with open('some/file/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


# Word Tagging
class WordTagging:

    # Constructor
    def __init__(self):
        self.word_dict = {}
        self.word_color = {
            'Nomina': 'has-text-link',
            'Adjektiva': 'has-text-primary',
            'Verba': 'has-text-warning',
            'Verba-Definitif': 'has-text-warning',
            'Adverbia': 'has-text-info',
            'Preposisi': 'has-text-grey-light',
            'Interjeksi': 'has-text-info',
            'Konjungsi': 'has-text-grey-light',
            'Pronomina': 'has-text-success',
            'Lain-lain': 'has-text-danger',
            'Numeralia': 'has-text-info',
            'Separator': 'has-text-grey-light',
            'Titik': 'has-text-grey-light',
        }
        self.add_root_word()

    # Return word color by type
    def get_word_color(self):
        return self.word_color

    # Add base word & type dictionary
    def add_root_word(self):
        word_root = Katadasar.objects.values_list('katadasar', flat=True)
        word_type = Katadasar.objects.values_list('tipe_katadasar', flat=True)
        self.word_dict = dict(zip(word_root, word_type))

    # Identify type of word
    def identify_word(self, stemmed_word, origin_word ):
        word_type = {'tipe_katadasar': 'Lain-lain'}

        if stemmed_word in self.word_dict:

            if origin_word.lower() == 'adalah' or origin_word.lower() == 'merupakan':
                return 'Verba-Definitif'

            elif stemmed_word == origin_word.lower():
                return self.word_dict[stemmed_word]

            elif origin_word.lower().find('me') == 0 or origin_word.lower().find('di') == 0:
                return 'Verba'

            elif origin_word.lower().find('pe') == 0 and re.match(r'^(.*)(an|nya)$', origin_word.lower()) or origin_word.lower().find('ke') == 0:
                return 'Nomina'

            elif origin_word.lower().find('ter') == 0 or origin_word.lower().find('se') == 0:
                return 'Preposisi'

            elif origin_word.lower().find('ber') == 0:
                return 'Adjektiva'

            else:
                return self.word_dict[stemmed_word]

        elif origin_word.lower() == 'dll' or origin_word.lower() == 'dsb' or origin_word.lower() == 'etc':
            return 'Konjungsi'

        elif origin_word.lower() == ',':
            return 'Separator'
        
        elif origin_word.lower() == '.':
            return 'Titik'
        
        elif re.match(r'[0-9]', origin_word.lower()):
            return 'Numeralia'

        else:
            return word_type['tipe_katadasar']

    # Identify each word in sentence
    def identify_text(self, stemmed_sentence, origin_sentence):
        type_list = []
        for i, stemmed_word in enumerate(stemmed_sentence):
            type_temp = self.identify_word(stemmed_word, origin_sentence[i])
            type_list.append({'type': type_temp, 'color':self.word_color[type_temp]})
        return type_list


# Processing steps
class Processing:

    def __init__(self):
        self.word_phrase_list = {}
        self.word_phrase_list_array = []
        self.word_graph = nx.DiGraph()
        self.word_graph_undirect = nx.Graph()
        self.word_score_list = {}

    def get_word_phrase_list(self):
        return self.word_phrase_list

    def get_in_edges(self, keys):
        return [(key) for key in self.word_graph.predecessors(keys)]

    def get_out_edges(self, keys):
        return [(key) for key in self.word_graph.successors(keys)]

    def get_undirect_edges(self, keys):
        return [(key) for key in self.word_graph_undirect.neighbors(keys)]

    def get_word_score_list(self):
        sorted_score = sorted(self.word_score_list.items(), key=lambda kv: kv[1], reverse=True)
        sorted_score[10:len(sorted_score)] = []
        return sorted_score

    def get_all_edges(self, undirect=False):
        all_edges = {}
        if undirect:
            for key, value in self.word_phrase_list.items():
                all_edges.update({key: {
                    'neighbors': self.get_undirect_edges(key),
                }})
        else:
            for key, value in self.word_phrase_list.items():
                all_edges.update({key: {
                    'in': self.get_in_edges(key),
                    'out': self.get_out_edges(key),
                }})
        return all_edges

    def add_key_candidate(self, keys, key_type, sentence_id, lexical_index):
        if keys in self.word_phrase_list:
            has_sentence = self.word_phrase_list[keys]['has_sentence']
            has_sentence.append(sentence_id)
            temp_lexical_index =  self.word_phrase_list[keys]['lexical_index']
            temp_lexical_index.append(lexical_index)
            self.word_phrase_list.update({
                keys:{
                    'type':key_type, 
                    'has_sentence': has_sentence, 
                    'lexical_index': temp_lexical_index
                }
            })
        else:
            self.word_phrase_list.update({
                keys: {
                    'type':key_type, 
                    'has_sentence': [sentence_id], 
                    'lexical_index': [lexical_index]
                }
            })
        self.word_phrase_list_array.append(keys)

    def process_word(self, sentence, basic=False):
        skip_word = 0
        lexical_index = 0
        sentence_id = 0

        for i, word in enumerate(sentence):

            if skip_word == 0:

                if word['type'] == 'Nomina' or word['type'] == 'Lain-lain':
                    keysid1 = word['origin']

                    if i < len(sentence)-1:
                        if sentence[i+1]['type'] == 'Nomina' or sentence[i+1]['type'] == 'Lain-lain':
                            if word['type'] != 'Lain-lain' and sentence[i+1]['type'] == 'Lain-lain': continue
                            
                            keysid2 = sentence[i+1]['origin']
                            keys2 = keysid1 + ' ' + keysid2

                            if i < len(sentence)-2:

keyextractor/templates/keyextractor/article.html
{% extends "keyextractor/base.html" %}

{% block content %}
    
    {% if article_list %}

        {% for article in article_list %}
            
            <div class="card">
                <article class="card-content media">
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong><a href="{% url 'keyextractor:article_detail' article.id %}"> {{ article.title }} </a></strong>
                                <br>

                                <p class="has-text-justified">
                                    {{ article.content.abstrak|safe|truncatechars:"500" }} 
                                    {% if article.content.abstrak|length > 500 %}
                                        <a href="{% url 'keyextractor:article_detail' article.id %}">Selengkapnya</a>
                                    {% endif %}
                                </p>

                            </p>
                        </div>
                    </div>
                </article>
            </div>

        {% endfor %}

        <br>
        <nav class="pagination is-rounded" role="navigation" aria-label="pagination">

            {% if article_list.has_previous %}
                <a class="pagination-previous" href="?page={{ article_list.previous_page_number }}" title="Go to previous page">Sebelumnya</a>
            {% endif %}

            {% if article_list.has_next %}
                <a class="pagination-next" href="?page={{ article_list.next_page_number }}" title="Go to next page">Selanjutnya</a>
            {% endif %}

            <ul class="pagination-list">
                {% for page in paginator.page_range %}
                    {% if page == article_list.number %}
                        <li><a class="pagination-link is-current" aria-label="Page {{ page }}" aria-current="page"> {{ page }} </a></li>
                    {% else %}
                        <li><a href="?page={{ page }}" class="pagination-link" aria-label="Goto page {{ page }}"> {{ page }} </a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>

    {% else %}
    
        <div class="has-text-centered">
            <br><br><br>
            <h4>No Article available.</h4><br>
            <a href="{% url 'keyextractor:article_create' %}" class="button is-primary is-large">Create New Article</a>
        </div>
        
    {% endif %}

{% endblock %}

keyextractor/templates/keyextractor/article_analyze_process.html
{% extends "keyextractor/article_analyze.html" %}

{% block analyze_keyword %}

    

{% endblock %}

keyextractor/templates/keyextractor/article_create.html
{% extends "keyextractor/base.html" %}

{% block content %}
    
    <div class="columns">
        
        <div class="card column is-three-quarters">
            <div class="card-content">
                
                {% if article.id %}

                {% else %}
                <form action="{% url 'keyextractor:import_pdf' %}" method="post" enctype="multipart/form-data" name="form_pdf">
                    {% csrf_token %}
                    <input type="file" class="button" name="file">
                    <input type="submit" class="button is-primary" value="Import PDF">
                    <br><br>
                </form>
                {% endif %}

                {% if article.id %}
                <form action="{% url action article.id %}" method="post">
                {% else %}
                <form action="{% url action %}" method="post">
                {% endif %}
                    {% csrf_token %}
                    <div class="field">
                        <label class="label">Judul</label>
                        <div class="control">
                            <input type="text" class="input" name="title" placeholder="Judul Artikel" value="{{article.title}}">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Isi</label>
                        <div class="control">
                            <textarea class="textarea" name="content" placeholder="Tulis artikel disini ..." rows="10">{{article.content}}</textarea>
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Original Keyword</label>
                        <div class="control">
                            <input type="text" class="input" name="original_keyword" placeholder="Setiap kata kunci dipisah dengan tanda koma (,) dan spasi (Contoh: keyword1, keyword2)" value="{{article.original_keyword}}">
                        </div>
                    </div>
                    <br>
                    
                    <div class="control">
                        <input type="submit" class="button is-primary" value="{{ type }}">
                    </div>

                </form>
            </div>
        </div>

        {% block side_panel %} {% endblock %}

    </div>

{% endblock %}

keyextractor/templates/keyextractor/article_detail.html
{% extends "keyextractor/base.html" %}

{% block content %}
    
    <div class="card">
        <article class="card-content media">
            <div class="media-content">
                <div class="content">
                    <h1 class="title">{{ article.title }}</h1>
                    
                    <p class="has-text-justified">
                        <b>Abstrak</b><br>
                        {{ article.content.abstrak }}<br>
                        <p id="article_isi" class="has-text-justified"><b>Isi</b><br> {{ article.content.isi }} </p>
                        <a href="#" id="read_toggle" data-content="toggle-text">Selengkapnya</a>
                    </p>

                    {% if article.original_keyword %}
                        <p><b>Kata Kunci : </b> {{ article.original_keyword }} </p>
                    {% endif %}

                </div>
            </div>
        </article>
        <div class="card-footer">
            <div class="dropdown card-footer-item">
                <div class="dropdown-trigger">
                    <a aria-haspopup="true" aria-controls="dropdown-menu">
                        <span>Ekstrak Kata Kunci</span>
                        <span class="icon is-small">
                            <i class="fas fa-angle-down" aria-hidden="true"></i>
                        </span>
                    </a>
                </div>
                <div class="dropdown-menu" id="dropdown-menu" role="menu">
                    <div class="dropdown-content">
                        <a href="{% url 'keyextractor:article_analyze' article.id %}" class="dropdown-item">Modified TextRank</a>
                        <a href="{% url 'keyextractor:article_analyze_basic' article.id %}" class="dropdown-item">Original TextRank</a>
                    </div>
                </div>
            </div>

            {% if article.extracted_keyword or article.extracted_keyword_basic %}
                <a href="{% url 'keyextractor:reset_extraction' article.id %}" class="card-footer-item">Reset Ekstraksi</a>
            {% endif %}
            <a href="{% url 'keyextractor:article_update' article.id %}" class="card-footer-item">Edit Artikel</a>
            <a onclick="if(confirm('Apakah anda yakin ingin menghapus artikel ini ??')){ location.href='{% url 'keyextractor:article_delete' article.id %}' }" class="card-footer-item">Hapus Artikel</a>
        </div>
    </div>

    <br>
    {% block analyze_keyword %}{% endblock %}

{% endblock %}

keyextractor/templates/keyextractor/article_pdf.html
{% extends "keyextractor/base.html" %}

{% block content %}

    <p>{{ data }}</p>
    
{% endblock %}

keyextractor/templates/keyextractor/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Keyword Extractor</title>
        <link rel="stylesheet" type="text/css" href="{% static 'keyextractor/css/bulma.min.css' %}">
        <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>        
    <body>
        <section class="hero is-primary">
            <div class="hero-body">
                <div class="container">
                    <a href="{% url 'keyextractor:home' %}"><h1 class="title">Keyword Extractor</h1></a>
                    <h2 class="subtitle">Ekstrak kata kunci dari artikel secara otomatis!</h2>
                </div>
            </div>
            <!-- <div class="navbar-menu container">
                <div class="navbar-start">
                    <a href="{% url 'keyextractor:home' %}" class="navbar-item">Home</a>
                    <a class="navbar-item">Profile</a>
                    <a class="navbar-item">About</a>
                </div>
                <div class="navbar-end">
                    <a class="navbar-item">Help</a>
                </div>
            </div> -->
        </section>

        <section class="section">
            <div class="container">

                {% if error_message %}<span class="tag is-danger">{{ error_message }}</span><br><br>{% endif %}

                {% if article_list %}
                    <div class="columns">
                        <div class="column is-7">
                            <a href="{% url 'keyextractor:article_create' %}" class="button is-primary">Buat Artikel Baru</a>&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'keyextractor:statistics' %}" class="button">Lihat Statistik</a>&nbsp;&nbsp;&nbsp;

                            <div class="dropdown">
                                <div class="dropdown-trigger">
                                    <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
                                        <span>Ekstraksi</span>
                                        <span class="icon is-small">
                                            <i class="fas fa-angle-down" aria-hidden="true"></i>
                                        </span>
                                    </button>
                                </div>
                                <div class="dropdown-menu" id="dropdown-menu" role="menu">
                                    <div class="dropdown-content">
                                        <a href="{% url 'keyextractor:extract_all_keyword' %}" class="dropdown-item">Ekstrak mengg. modified TextRank</a>
                                        <a href="{% url 'keyextractor:extract_all_keyword_basic' %}" class="dropdown-item">Ekstrak mengg. original TextRank</a>
                                        <hr class="dropdown-divider">
                                        <a href="{% url 'keyextractor:reset_all_extraction' %}" class="dropdown-item">Reset Semua Ekstraksi</a>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <div class="column">
                            <p class="inline-block has-text-right">Halaman {{article_list.number}} dari {{paginator.num_pages}} -- Menampilkan {{article_list.start_index}}-{{article_list.end_index}} dari {{paginator.count}} artikel </p>
                        </div>
                    </div>
                {% endif %}

                {% block content %}{% endblock %}
                
            </div>
        </section>

        <script>
            $(document).ready(function(){

                $("#analyze_process").hide();
                $("#testing_detail").hide();
                $("#article_isi").hide();

                $("#extraction_detail_btn").click(function(){
                    $("#analyze_process").toggle(0, function() {
                        $('html, body').animate({
                            scrollTop: $("#analyze_process").offset().top
                        }, 500)
                    });
                });

                $("#testing_detail_btn").click(function(){
                    $("#testing_detail").toggle(0, function() {
                        $('html, body').animate({
                            scrollTop: $("#testing_detail").offset().top
                        }, 500)
                    });
                });
                
                $("#read_toggle").click(function () {
                    var txt = $("#article_isi").is(':visible') ? 'Selengkapnya' : 'Lihat Sedikit';
                    $("#read_toggle").text(txt);
                    $('#article_isi').slideToggle(200);
                });

            });

            var dropdown = document.querySelector('.dropdown');
            dropdown.addEventListener('click', function(event) {
                event.stopPropagation();
                dropdown.classList.toggle('is-active');
            });
        </script>

    </body>
</html>

keyextractor/templates/keyextractor/side_panel.html
<!-- {% extends "keyextractor/article_create.html" %} -->

{% block side_panel %}

    <div class="card column">
        <div class="card-content">
            <ul>
                <li><a> Option 1</a></li>
                <li><a> Option 2</a></li>
                <li><a> Option 3</a></li>
            </ul>
        </div>
    </div>

{% endblock %}

keyextractor/templates/keyextractor/statistics.html
{% extends "keyextractor/base.html" %}

{% block content %}

    <h1 class="title">Statistik</h1>
    <div class="card">
        <article class="card-content media">
            <div class="media-content">
                <div class="content columns">
                    <div class="column is-6">
                        <b class="has-text-danger">Modified TextRank</b>
                        <ul>
                            <li class="has-text-danger"><b>Rata-rata Akurasi:</b> {{ average_acc }} </li>
                            <li class="has-text-danger"><b>Akurasi Tertinggi:</b> {{ best_accuracy }} </li>
                            <li class="has-text-danger"><b>Rata-rata waktu ekstraksi:</b> {{ average_time }} ms/article </li>
                            <li class="has-text-danger"><b>Total waktu ekstraksi:</b> {{ extraction_time }} ms </li>
                        </ul>
                    </div>
                    <div class="column is-6">
                        <b>Original TextRank</b>
                        <ul>
                            <li><b>Rata-rata Akurasi:</b> {{ average_acc_basic }} </li>
                            <li><b>Akurasi Tertinggi:</b> {{ best_accuracy_ori }} </li>
                            <li><b>Rata-rata waktu ekstraksi:</b> {{ average_time_basic }} ms/article </li>
                            <li><b>Total waktu ekstraksi:</b> {{ extraction_time_basic }} ms </li>
                        </ul>
                    </div>
                </div>
            </div>
        </article>
    </div>
    <div class="card">
        <div class="card-content">
            <div class="content">
                <table class="table is-fullwidth is-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Judul</th>
                            <th>Akurasi Modified</th>
                            <th>Waktu Ekstraksi</th>
                            <th>Akurasi Original</th>
                            <th>Waktu Ekstraksi</th>
                        </tr>
                    </thead>
                    
                    <tbody>

                        {% for article in data %}
                        <tr>
                            <th> {{article.id}} </th>
                            <td><strong><a href="{% url 'keyextractor:article_detail' article.id %}"> {{ article.title|safe|truncatechars:"50" }} </a></strong></td>
                            <td class="has-text-danger"> {{ article.accuracy.f_measure|safe|truncatechars:"8" }} </td>
                            <td class="has-text-danger"> {{ article.load_time }}</td>
                            <td> {{ article.accuracy_ori.f_measure|safe|truncatechars:"8" }} </td>
                            <td> {{ article.load_time_ori }}</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}