auths/urls.py
from django.urls import path

from . import views

app_name = 'auths'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout, name='logout'),

    path('home/', views.home_view, name='home'),
    path('article/', views.article_view, name='article'),
    path('article_create/', views.article_create_view, name='article_create'),
    path('article_create_post/', views.article_create_post, name='article_create_post'),
    path('<int:article_id>/article_detail/', views.article_detail_view, name='article_detail'),

    path('login_post/', views.login_post, name='login_post'),
    path('register_post/', views.register_post, name='register_post'),

    path('<int:user_id>/update_view/', views.update_view, name='update_view'),
    path('<int:user_id>/update_post/', views.update_post, name='update_post'),

    path('<int:user_id>/delete/', views.delete, name='delete'),
]

simpleauth/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auths/', include('auths.urls')),
    path('keyextractor/', include('keyextractor.urls')),
    path('admin/', admin.site.urls),
]

auths/models.py
from django.db import models


class User(models.Model):
    fullname = models.CharField(max_length=100)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.fullname

class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

auths/views.py
from django.shortcuts import render
from django.views import View, generic
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from .models import User, Article

def index_view(request):
    try:
        sess = request.session['username']
    except(KeyError):
        return render(request, 'auths/index.html')
    else:
        return HttpResponseRedirect(reverse('auths:home'))

def home_view(request):
    try:
        sess = request.session['username']
    except(KeyError):
        return render(request, 'auths/index.html', {
            'error_message': "You haven't been login yet.",
        })
    else:
        user_list = User.objects.all()
        context = {'user_list': user_list}
        return render(request, 'auths/home.html', context)


def login_view(request):
    return render(request,'auths/login.html')

def register_view(request):
    return render(request,'auths/register.html')

def logout(request):
    try:
        del request.session['user_id']
        del request.session['username']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('auths:index'))

def login_post(request):
    try:
        user_data = User.objects.get(username=request.POST['username'])
    except (KeyError, User.DoesNotExist):
        return render(request, 'auths/login.html', {
            'error_message': "Invalid Username",
        })
    else:
        if user_data.password == request.POST['password']:
            request.session['user_id'] = user_data.id
            request.session['username'] = user_data.username
            return HttpResponseRedirect(reverse('auths:home'))
        else:
            return render(request, 'auths/login.html', {
            'error_message': "Invalid Password.",
        })

def register_post(request):
    try:
        user_data = User(
            fullname=request.POST['fullname'],
            username=request.POST['username'],
            password=request.POST['password']
        )
    except (KeyError, User.DoesNotExist):
        return render(request, 'auths/register.html', {
            'error_message': "You haven't been insert data.",
        })
    else:
        user_data.save()
        request.session['user_id'] = user_data.id
        request.session['username'] = user_data.username
        return HttpResponseRedirect(reverse('auths:home'))

def update_view(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
    except(User.DoesNotExist):
        return render(request, 'auths/update.html', {
            'error_message': "User not available.",
        })
    else:
        return render(request,'auths/update.html', {'user': user})

def update_post(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
        fullname = request.POST['fullname']
        username = request.POST['username']
        password = request.POST['password']

    except (KeyError, User.DoesNotExist):
        return render(request, 'auths/update.html', {
            'error_message': "Update Failed.",
        })
    else:
        user.fullname = fullname
        user.username = username
        user.password = password
        user.save()
        return HttpResponseRedirect(reverse('auths:home'))

def delete(request, user_id):
    try:
        user = User.objects.get(pk=user_id)
    except (User.DoesNotExist):
        return render(request, 'auths/home.html', {
            'error_message': "Delete Failed.",
        })
    else:
        user.delete()
        return HttpResponseRedirect(reverse('auths:home'))

def article_view(request):
    try:
        user_id = request.session['user_id']
        user = User.objects.get(pk=user_id)
    except(KeyError, User.DoesNotExist):
        return render(request, 'auths/index.html', {
            'error_message': "You haven't been login yet.",
        })
    else:
        article_list = user.article_set.all()
        context = {'article_list': article_list}
        return render(request, 'auths/article.html', context)

def article_create_view(request):
    return render(request, 'auths/article_create.html')

def article_create_post(request):
    try:
        user_id = request.session['user_id']
        user = User.objects.get(pk=user_id)
        title = request.POST['title']
        content = request.POST['content']
    except (KeyError, User.DoesNotExist):
        return render(request, 'auths/article_create.html', {
            'error_message': "Failed to create article",
        })
    else:
        user.article_set.create(title=title, content=content)
        return HttpResponseRedirect(reverse('auths:article'))

def article_detail_view(request, article_id):
    try:
        article = Article.objects.get(pk=article_id)
    except(Article.DoesNotExist):
        return render(request, 'auths/home.html', {
            'error_message': "Failed to load article",
        })
    else:
        return render(request,'auths/article_detail.html', {'article': article})

auths/templates/auths/article.html
{% extends "auths/base.html" %}

{% block content %}
    <div class="control">
        <a href="{% url 'auths:article_create' %}" class="button is-primary">Create New Article</a>
    </div>
    <br>
    {% if article_list %}
        {% for article in article_list %}
            <div class="card">
                <article class="card-content media">
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong><a href="{% url 'auths:article_detail' article.id %}"> {{ article.title }} </a></strong>
                                <br>
                                {{ article.content }}
                            </p>
                        </div>
                    </div>
                </article>
            </div>
        {% endfor %}
    {% else %}
        <p>No Article available.</p>
    {% endif %}
{% endblock %}

auths/templates/auths/article_create.html
{% extends "auths/base.html" %}

{% block content %}
    
    <div class="columns">
            
        <div class="card column is-three-quarters">
            <div class="card-content">
                
                <form action="{% url 'auths:article_create_post' %}" method="post">
                    {% csrf_token %}
                    <div class="field">
                        <label class="label">Title</label>
                        <div class="control">
                            <input type="text" class="input" name="title" placeholder="Your Article Title">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Content</label>
                        <div class="control">
                            <textarea class="textarea" name="content" placeholder="Write your content here..." rows="8"></textarea> <br>
                        </div>
                    </div>

                    <div class="control">
                        <input type="submit" class="button is-primary" value="Create">
                    </div>

                </form>
            </div>
        </div>

        {% block side_panel %} {% endblock %}

    </div>

{% endblock %}

auths/templates/auths/article_detail.html
{% extends "auths/base.html" %}

{% block content %}
    
    <div class="columns">
        <div class="card column is-three-quarters">
            <div class="card-content">
                <div class="container">
                    <h1 class="title">{{ article.title }}</h1>
                    <p>{{ article.content }}</p>
                </div>
            </div>
        </div>

        {% block side_panel %} {% endblock %}
        
    </div>
    

{% endblock %}

auths/templates/auths/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello User!</title>
        <link rel="stylesheet" type="text/css" href="{% static 'auths/css/bulma.min.css' %}">
        <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
    </head>        
    <body>
        <section class="hero is-primary">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title">Simple Authentification!</h1>
                    <h2 class="subtitle">The Simple Authentification and Manage User Data Application</h2>
                </div>
            </div>
            <div class="navbar-menu container">
                <div class="navbar-start">
                    <a href="{% url 'auths:home' %}" class="navbar-item">Home</a>
                    <a class="navbar-item">Profile</a>
                    <a href="{% url 'auths:article' %}" class="navbar-item">Article</a>
                </div>
                <div class="navbar-end">
                    <a href="{% url 'auths:logout' %}" class="navbar-item">Logout</a>
                </div>
            </div>
        </section>

        <section class="section">
            
            <div class="container">

                {% if error_message %}<span class="tag is-danger">{{ error_message }}</span><br><br>{% endif %}

                {% block content %}{% endblock %}
                
            </div>
        </section>
    </body>
</html>

auths/templates/auths/base_index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Hello User!</title>
        <link rel="stylesheet" type="text/css" href="{% static 'auths/css/bulma.min.css' %}">
        <script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
    </head>        
    <body>
        <section class="hero is-primary">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title">Simple Authentification!</h1>
                    <h2 class="subtitle">The Simple Authentification and Manage User Data Application</h2>
                </div>
            </div>
        </section>

        <section class="section">
            <div class="container">

                {% if error_message %}<span class="tag is-danger">{{ error_message }}</span><br><br>{% endif %}

                {% block content %}{% endblock %} 

            </div>
        </section>
    </body>
</html>

auths/templates/auths/home.html
{% extends "auths/base.html" %}

{% block content %}
    {% if user_list %}
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in user_list %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.fullname }}</td>
                    <td>{{ user.username }}</td>
                    <td>
                        <a href="{% url 'auths:update_view' user.id %}" class="button is-primary is-small">Edit</a>
                        <a onclick="if(confirm('Apakah anda yakin ingin menghapus user ini ??')){ location.href='{% url 'auths:delete' user.id %}' }" class="button is-danger is-small">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No User available.</p>
    {% endif %}
    
{% endblock %}

auths/templates/auths/index.html
{% extends "auths/base_index.html" %}

{% block content %}

    <ul>
        <li><a class="button is-primary is-large" href="{% url 'auths:register' %}">Getting Started</a></li>
        <br>
        <li><a class="button" href="{% url 'auths:login' %}">Login</a></li>
    </ul>

{% endblock %}

auths/templates/auths/login.html
{% extends "auths/base_index.html" %}

{% block content %}

    <div class="columns">
        
    <div class="card column is-half">
        <div class="card-content">
            <h1 class="title"> Login! </h1>
            <form action="{% url 'auths:login_post' %}" method="post">
                {% csrf_token %}
                <div class="field">
                    <div class="control">
                        <input type="text" class="input" name="username" placeholder="Username">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <input type="password" class="input" name="password" placeholder="Password"><br>
                    </div>
                </div>

                <div class="control">
                    <input type="submit" class="button is-primary" value="Sign In">
                </div>

            </form>
        </div>
    </div>

    </div>

{% endblock %}

auths/templates/auths/register.html
{% extends "auths/base_index.html" %}

{% block content %}

    <div class="columns">

        <div class="card column is-half">
            <div class="card-content">
                <h1 class="title"> Register! </h1>

                <form action="{% url 'auths:register_post' %}" method="post">
                    {% csrf_token %}
                    <div class="field">
                        <div class="control">
                            <input type="text" class="input" name="fullname" placeholder="Your Name">
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <input type="text" class="input" name="username" placeholder="Username">
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <input type="password" class="input" name="password" placeholder="Password"><br>
                        </div>
                    </div>

                    <div class="control">
                        <input type="submit" class="button is-primary" value="Register">
                    </div>
                    
                </form>

            </div>
        </div>
    </div>
{% endblock %}

auths/templates/auths/side_panel.html
{% extends "auths/article_create.html" %}

{% block side_panel %}

    <div class="card column">
        <div class="card-content">
            <ul>
                <li><a> Option 1</a></li>
                <li><a> Option 2</a></li>
                <li><a> Option 3</a></li>
            </ul>
        </div>
    </div>

{% endblock %}

auths/templates/auths/update.html
{% extends "auths/base.html" %}

{% block content %}

    <div class="columns">

        <div class="card column is-half">
            <div class="card-content">
                <h1 class="title"> Update! </h1>

                <form action="{% url 'auths:update_post' user.id %}" method="post">
                    {% csrf_token %}
                    <div class="field">
                        <div class="control">
                            <input type="text" class="input" name="fullname" placeholder="Your Name" value="{{ user.fullname }}">
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <input type="text" class="input" name="username" placeholder="Username" value="{{ user.username }}">
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <input type="password" class="input" name="password" placeholder="Password" value="{{ user.password }}"><br>
                        </div>
                    </div>

                    <div class="control">
                        <input type="submit" class="button is-primary" value="Update">
                    </div>
                    
                </form>

            </div>
        </div>
    </div>
{% endblock %}